### PR TITLE
docs: Add note on multi-platform image building

### PR DESCRIPTION
**Pull request by ab91**
### Description

I added a note regarding the need for building images for multiple platforms. Myself and others ran into the below error during our initial HTO run attempts, which could have been avoided by building the docker image for the `AMD64` architecture:

`"ERR_INVALID_IMAGE_ARCHITECTURE\"`

I've requested @steilerDev as an additional reviewer for this, to help ensure I'm communicating this properly.

### Motivation and Context

This change aims to prevent our users from experiencing this error, instead of needing to work backwards to troubleshoot it, possibly resulting in a bad initial experience, delayed/preventing adoption.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [X] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by steilerDev — COMMENTED** [review]
I would not say 'for example' - because this flag is necessary on every non-amd64 platform (not specific to Apple).

I'd propose the following:
> Sauce Labs Hosted Orchestration only supports images built on the `amd64` architecture. If you are building your docker image on a machine with a different architecture, use the [--platform flag](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images) targeting `linux/amd64` to build an image compatible with our test runners.

**Comment by steilerDev** [comment]
lgtm

**Review by aliciakrebs — APPROVED** [review]

**Comment by aliciakrebs** [comment]
This will be merged with https://github.com/saucelabs/sauce-docs/pull/1907 after that PR is approved by TCD team.

**Comment by aliciakrebs** [comment]
@ab91, These changes have been merged with this [PR](https://github.com/saucelabs/sauce-docs/pull/1907). Thanks!

**Pull request closed without merging**
