### PR TITLE
STT Documentation February Updates

### PR DESCRIPTION
**Pull request by spider-sauce**
### Description

* Updated `/testrunner-toolkit/configuration` and moved all basic syntax refs to a new page: `/testrunner-tookit/configuration/basic`
* Updated `/testrunner-tookit/configuration/cypress` with minor formatting changes.
* Added a few new fields to `testrunner-toolkit/configuration/basic`: `concurrency`, `browser/browserName`, etc.
* Overhauled the **Running Tests** page to include information about how to run tests against a local app server / `localhost` app.
* Cross-linked the ☝️ on this page: `/web-apps/automated-testing/cypress` with a warning box
### Motivation and Context

Make the documentation more clear in terms of:
* Basic config syntax
* Framework-specific syntax
* Localhost deployment recommendations
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexplischke** [comment]
I guess `basic` is supposed to be the common configuration?

**Comment by spider-sauce** [comment]
> I guess `basic` is supposed to be the common configuration?

Yes, we can call it 'common syntax' or 'basic configuration' in the tree. Not sure what makes more sense, these changes were based on the slack thread Kunal created.

**Comment by alexplischke** [comment]
> > I guess `basic` is supposed to be the common configuration?
> 
> Yes, we can call it 'common syntax' or 'basic configuration' in the tree; not sure what makes more sense. These changes were based on the feedback in the [slack thread Kunal created](https://saucelabs.slack.com/archives/C011WGM40N6/p1613769441142700).

I personally like `common` (or `common syntax`) ✌️

**Comment by spider-sauce** [comment]
> > > I guess `basic` is supposed to be the common configuration?
> > 
> > 
> > Yes, we can call it 'common syntax' or 'basic configuration' in the tree; not sure what makes more sense. These changes were based on the feedback in the [slack thread Kunal created](https://saucelabs.slack.com/archives/C011WGM40N6/p1613769441142700).
> 
> I personally like `common` (or `common syntax`) ✌️

Ok I just changed it.

**Comment by KunalJain** [comment]
Looks great! Thank you so much! On the common syntax page, it would be nice to have a config towards the end as an example to showcase how all these keys are getting used together.

**Review by KunalJain — APPROVED** [review]

**Comment by spider-sauce** [comment]
> Looks great! Thank you so much! On the common syntax page, it would be nice to have a config towards the end as an example to showcase how all these keys are getting used together.

Will add after merge 😄

**Pull request merged**
