### PR TITLE
Added Azure to SC System Requirements doc

### PR DESCRIPTION
**Pull request by kimsauce**
### Description

Added Azure to SC system requirements (alongside AWS and GCE) per https://saucedev.atlassian.net/browse/TCD-1794. 

NOTE: Please ignore the commit re: Selenium -- pushed to wrong branch!

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/CONTRIBUTING.MD) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexh-sauce** [comment]
The network bandwidth should match the values from the `Expected network bandwidth (Mbps)` column on https://docs.microsoft.com/en-us/azure/virtual-machines/dav4-dasv4-series.

**Comment by alexh-sauce** [comment]
Oh, same with memory.

**Review by alexh-sauce — CHANGES_REQUESTED** [review]
Left some comments re the networking and memory values in the table.

**Comment by kimsauce** [comment]
> Left some comments re the networking and memory values in the table.

Hi @alexh-sauce , I've applied the memory & bandwidth changes from [here](https://docs.microsoft.com/en-us/azure/virtual-machines/dav4-dasv4-series). Would you be able to take a look --> https://github.com/saucelabs/sauce-docs/pull/739/files

I wasn't able to find your comments in the table. Do you have a link?

**Pull request merged**
