### PR TITLE
Change devices to simulators for Testcafe

### PR DESCRIPTION
**Pull request by wswebcreation**
When running the example I got this error.

21:18:50 ERR failed to execute run command error="the 'devices' keyword in your config is now reserved for real devices, please use 'simulators' instead"

This PR fixes the docs for it

**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sweeneyskirt-sl** [comment]
Hey @tianfeng92  -- are you aware of this doc request change from Wim? Have we made this change in the actual config.yml? The sample in the demo repo does not include any device config settings.

**Comment by tianfeng92** [comment]
@sweeneyskirt-sl yep. I remember this has been changed recently by @alexplischke

**Comment by sweeneyskirt-sl** [comment]
Okay. Thanks for the confirmation. This page has significantly changed since Wim submitted this ticket, so I'll take a look.

**Review by sweeneyskirt-sl — COMMENTED** [review]
This looks good to me, @wswebcreation. Thanks for catching the oversight.

**Review by sweeneyskirt-sl — APPROVED** [review]

**Pull request merged**
