### PR TITLE
Formatting fixes for admonitions

### PR DESCRIPTION
**Pull request by lysannep**
### Description
Updates formatting/spacing for admonitions (apologies for the large PR -- will commit by section in the future so there are less changed files to review).

### Motivation and Context
[TCD-2654](https://saucedev.atlassian.net/browse/TCD-2654)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

[TCD-2654]: https://saucedev.atlassian.net/browse/TCD-2654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lysannep** [comment]
To do: Add the prettier-ignore tag

**Comment by lysannep** [comment]
> **To do:** Add the prettier-ignore tag

Done.

**Comment by aliciakrebs** [comment]
@lysannep  James is going to revert the changes for APIF on-prem  and add the folder to the prettier ignore. I don't think those files need to be included in this fix.

**Review by aliciakrebs — APPROVED** [review]

**Comment by lysannep** [comment]
> @lysannep James is going to revert the changes for APIF on-prem and add the folder to the prettier ignore. I don't think those files PIF on-prem to be included in this fix.

Removed.

**Pull request merged**
