### PR TITLE
Quickstart new landpage

### PR DESCRIPTION
**Pull request by discombobulateme**
### Description
Re-styled current landpage to match a quick start approach based on this design: https://www.figma.com/file/BRGEgNyVC8AWfLqagNHbnb/Docs-Community-Resource-Home?node-id=0%3A1

### Motivation and Context
Requested by content team, based on usability analysis.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by spider-sauce — APPROVED** [review]
LGTM 👍

**Comment by sweeneyskirt-sl** [comment]
Hey @discombobulateme -- I pulled this branch so I could have a sneak peak at the new page -- it looks great! So clean. The only thing I noticed is that the line under the search bar that has the Popular Searches key links -- the red color doesn't look quite right to me -- is that the official "sauce red"?

**Comment by spider-sauce** [comment]
> 

I fixed the link color in the latest commit

**Comment by discombobulateme** [comment]
Hi @sweeneyskirt-sl ! I used the darker Sauce red to comply with accessibility contrast. 
:) 
We can leave the regular Sauce for now, but we should find a better design accessible solution in the near future :)
Thank you for checking it!

**Pull request merged**
