### PR TITLE
Rebranding

### PR DESCRIPTION
**Pull request by discombobulateme**
This PR is applying Sauce Labs' new design system to Docs

### CODE REVIEW

**Comment by lysannep** [comment]
@discombobulateme ~ In dark mode, the content in the box cards is not visible as the text is white on a white background. 
Screenshot 2023-02-10 at 1 27 17 PM
Can we fix this?

**Comment by lysannep** [comment]
@discombobulateme  ~ Are the colour contrasts for light and dark mode compliant with WCAG? Is that something that we check for?

**Comment by lysannep** [comment]
@discombobulateme ~ We should also update the 404 error page.
 
Screenshot 2023-02-10 at 1 54 00 PM

**Comment by aliciakrebs** [comment]
Consider updating the  Collapsible text block <details>. It is still style with blue: 
image

**Review by spider-sauce — APPROVED** [review]
LGTM 👍

**Pull request merged**
