### PR TITLE
use repo tags when referencing code

### PR DESCRIPTION
**Pull request by titusfortner**
### Description
I'm proposing we change all code references in our docs from branches and commits to use tags

### Motivation and Context
Referencing github code with a branch name risks the code getting moved or files being renamed or deleted, which will cause the documentation to be wrong.
Referencing github code with a commit is better, but it has no contextual meaning and will be difficult to know if/when it goes out of date.

With tags we can periodically review that the reference in the docs matches the latest code in the repo.

I used `website-{version}` but maybe it would have been better to use `docs-{version}`? 
Just something consistent to make it easier to see where we are pulling things.

Finally, these tags are only for the `saucelabs-training/demo-{language}` repos, since those are the ones I've done anything with. If we agree this is the right approach, we should figure out the naming convention and tag the other repos and update them references to them.

What do people think?

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by christian-bromann** [comment]
> What do people think?

I like the idea of this proposal. I would love to see a process document that describes how releases are done. How does one make a change to a code example and what is the process to get it ultimately released on the production version?

**Comment by titusfortner** [comment]
Yeah, the problem is that there's no way to make sure from the code source side that nothing that is changing is being referenced in the docs. I guess I'm thinking update the minor version of tags for code that needs to be added, and then periodically (~6mo? ~1yr?) do a review to make sure everything is referencing the latest code and update everything to a new major version. I'm not saying it isn't drudge work, or easy to maintain, but, I think this is better than the other alternatives.

**Comment by spider-sauce** [comment]
@titusfortner I like this idea too. Why not have both:

-  `website-{version}`, to indicate something is referenced in the product/app, and 
- `docs-{version}` to indicate something is referenced in `sauce-docs`

Also, should we do semantic versioning? Might not be necessary if it's just scripts and one-off examples. Once we agree on naming conventions I can make a process doc and add to our contributor guide.

**Comment by titusfortner** [comment]
ah, yeah I like doing both `website-` and `docs-` for additional reference

What I'm thinking is essentially like semantic versioning. When adding new code for referencing on the site in one place, bump the minor version and use it just for that example; when updating everything to make sure it's using the latest, bump the major version. So when we have a bunch of different things at 1.1, 1.4, 1.7, 1.12; we say it's time to do an audit and we try to update everything to latest and fix any code references that have changed.

Partly I'm thinking of this because I just did a huge revamp of `demo-java` repo to remove outdated things, update examples to use JUnit5 and leverage the SauceBindings test runners. I also moved the package names around so that they are all easier to work with in the project overall. So... stuff's going to break if we are just referencing files directly from main branch.

**Comment by diemol** [comment]
I like this idea as well, and I believe this PR can stay as it is to avoid incresing the scope. 

I think the tag naming does not really matter, because the tag needs to be aligned to whatever convention exists in the repo being linked to. For example, if we were going to link an example or a piece of documentation from WebdriverIO, we cannot expect that repo to have a given structure for their tags. I know the idea is to only reference Sauce owned examples, but this type of naming is sometimes hard to keep across different repos. From my point of view, what matters is that there is a tag, and something similar to SemVer would be ideal.

What this repo needs to address soon is what @christian-bromann mentions, the contribution guidelines and release process seems to be non existent. When I go and check the [README](https://github.com/saucelabs/sauce-docs#contributing), the contribution guide link is broken. We should improve those things if we expect customers to contribute to the docs as well, and in general, anyone who is not in Sauce.

**Comment by titusfortner** [comment]
@diemol most of the code references in our documentation should point to repos we own, where doing some kind of semver makes sense. If it's an external repo, we're much less likely to be referencing specific files or lines of code. Like, we'd link to the wdio documentation, not example code. If we needed example code, we'd create it in demo-js repo

**Comment by titusfortner** [comment]
The description for this isn't quite accurate any longer, and I don't feel like editing it.

As of last push:

* All of the demo-<language> repos have been tagged `docs-1.0`
* All of the references to demo-<language> repos have been updated to use the tags
* I verified that all of the code referencing the new tags is in fact referencing the correct code (there were broken references that I fixed)
* Reference tags for demo-<language> repos have had a title added now that it is supported
* This fixes a bug in Style Guide (keywords not tags)
* Adds a section on the use of `details` element in our codebase in style guide
* I got a little heavy in my edits on `virtual-devices` file while updating code references, so whoever is doing the Appium overhaul probably needs to weigh in on this, and I can pull it out into a separate thing if that's easier.

**Comment by sweeneyskirt-sl** [comment]
I added Titus' fork as a remote and checked out this branch so I could resolve some conflicts and get it up-to-date with our current build. I ran the build locally, so I am confident that the Algolia Key issue is the only factor in the build failure, so I am going to go ahead and merge this. Thank you, @titusfortner for all of your help getting this over the finish line.

**Review by sweeneyskirt-sl — APPROVED** [review]

**Pull request merged**
