### PR TITLE
Added API Testing how-to content and screenshots, and removed "how to" section

### PR DESCRIPTION
**Pull request by lauramthomas**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by LoryApiFortress — CHANGES_REQUESTED** [review]
NO!

**Comment by lauramthomas** [comment]
@LoryApiFortress No to what, specifically?

**Comment by LoryApiFortress** [comment]
@lauramthomas All, this is wrong! “How to guides” have a specific scope, explain how to do something. Composer page (and any other page like this one) shows what is the feature. These are two different kinds of docs that cannot be merged in a single doc.

**Comment by lauramthomas** [comment]
@LoryApiFortress 
1. Specific feedback is more helpful than "No!"
2. We have guidelines we follow for our content, as I mentioned previously. We do not use how-to guides, and we incorporate as much content into a single page as makes sense, since the nav and search functions are so robust. There are several other reasons that I removed the how-to guides section and incorporated the content in the composer.md file, not the least of which is that adding and removing whole pages of content risks breaking the site and causing issues for our users.

**Review by spider-sauce — APPROVED** [review]
LGTM 👍

**Review by lysannep — APPROVED** [review]

**Comment by lauramthomas** [comment]
Closing without merging changes because there have been multiple branches and updates since it was created and now it is out of date.

**Pull request closed without merging**
