### PR TITLE
HAR import content

### PR DESCRIPTION
**Pull request by lauramthomas**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kimsauce — CHANGES_REQUESTED** [review]
I think **Importing a HAR File** might be more closely aligned with these two docs, since it uses the same **Import** button:
- https://docs.saucelabs.com/api-testing/build-from-spec/
- https://docs.saucelabs.com/api-testing/import-postman-collection/

Related to this... I wanted to mention I had intended to combine all of these docs ("How to Create a Test") so that it mirrors this UI step:
HAR-file

**Review by lysannep — APPROVED** [review]

**Comment by lauramthomas** [comment]
@kimsauce I moved the content. Definitely makes more sense. Can you re-review and approve?

**Review by kimsauce — APPROVED** [review]
Looks good!!

**Comment by LoryApiFortress** [comment]
@lauramthomas There are some changes required:
1. This content cannot be put inside the "spec" page: Specs files are ONLY OpenAPI files, all the others files are supported files from our side but not Specs files
2. Title says "Importing a HAR file" but this is already available, here we are talking about "Import a HAR file from RDC job" that's a slightly different thing
3. This is not only for Android https://docs.saucelabs.com/mobile-apps/features/network-capture/#using-network-traffic-capture "Network Traffic Capture is a functionality that gives you the ability to record network traffic for HTTP/HTTPS requests during Android and iOS/iPadOS mobile app tests on real devices" 
4. There's no mention about there's a connection between the Network Capture in RDC and this feature: user need to activate the Network Capture in RDC to be able to see the HAR files in API Testing, this is not something "automatically done"
5. "On the project page, click Import OpenAPI/Postman, and then click Import Har from RDC Job." User is on HTTP Client, not on the project page
6. "In the folder, click a call name to view its details in the Body panel." : "click a call name" and "Body panel" means nothing. The correct one is "In the folder, click on a snapshot to view its details in the Response panel"

**Pull request merged**
