### PR TITLE
[DEVX-1164] Add latest runner version

### PR DESCRIPTION
**Pull request by tianfeng92**
This should be merged after releasing latest runner on cloud.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/CONTRIBUTING.MD) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by alexplischke — APPROVED** [review]

**Comment by sweeneyskirt-sl** [comment]
Resolved merge conflict from Felix's previous update.

**Review by sweeneyskirt-sl — CHANGES_REQUESTED** [review]
Hey @tianfeng92  -- These changes look fine, but they need to also be applied to the individual framework docs. I am sorry for the duplication, but Kunal really wanted each framework to have it's own "complete" info, so these supported version tables are also in the pages:
- /web-apps/automated-testing/cypress.md
- /web-apps/automated-testing/playwright.md
- /web-apps/automated-testing/puppeteer.md
- /web-apps/automated-testing/testcafe.md
Could you please add these to your PR? If you don't have time, I can checkout your branch and do it.

**Comment by tianfeng92** [comment]
@sweeneyskirt-sl I can do that today :) Thanks!

**Review by sweeneyskirt-sl — APPROVED** [review]
Thanks @tianfeng92 !

**Pull request merged**
