### PR TITLE
PERF-4603 removes Jira plugin documentation

### PR DESCRIPTION
**Pull request by flyingsaucervargas**
### Description

We are sunsetting Jira plugin, the first step would be to remove the documentation to prevent new customers from using it.

### Motivation and Context

The plugin is not longer maintained. https://saucedev.atlassian.net/browse/PERF-4603

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lysannep** [comment]
@flyingsaucervargas ~ Is there an official removal date? Before we completely remove the Jira doc page, we should deprecate it first by adding (deprecated) in the title and a deprecated badge.

That way, users are notified that the feature is not recommended for use and that it will be removed in the near future. As opposed to potential confusion about missing docs. Thoughts? @aoleszyn @aliciakrebs @lauramthomas

**Comment by aoleszyn** [comment]
> @flyingsaucervargas ~ Is there an official removal date? Before we completely remove the Jira doc page, we should deprecate it first by adding (deprecated) in the title and a deprecated badge.
> 
> That way, users are notified that the feature is not recommended for use and that it will be removed in the near future/ future release. As opposed to potential confusion about missing docs. Thoughts? @aoleszyn @aliciakrebs @lauramthomas

I contacted @thehannahm  regarding this subject and asked her to verify this information (I also added her as the reviewer of this PR). Also, I agree that it would be better to first deprecate the page and then remove the content :)

**Review by thehannahm — COMMENTED** [review]
@aoleszyn, @lysannep, you bring up a really good point, and typically I'd agree with you. However, this is a unique scenario: the JIRA integration is only used by a few people, and we need to transition the support of it away from the Insights team. The Backtrace team is starting to look at taking over this existing JIRA integration - or they'll build an entirely new JIRA integration. Is it worth marking this as deprecated for a month or two in this situation before pulling the documentation?

**Comment by flyingsaucervargas** [comment]
Hello @lysannep how can we proceed?

**Review by lysannep — APPROVED** [review]

**Comment by lysannep** [comment]
> 

@flyingsaucervargas Approved. You can merge these changes.

**Pull request merged**
