### PR TITLE
[DEVX-1362] Document async Flag

### PR DESCRIPTION
**Pull request by alexplischke**
Document the addition of the async flag.

### CODE REVIEW

**Review by tianfeng92 — APPROVED** [review]

**Comment by wswebcreation** [comment]
Cool

just saw this, do we also have docs to show how to check for the results

**Comment by alexplischke** [comment]
@wswebcreation Manually, by going to the sauce UI :D

The async flag was specifically introduced (based on customer requests) for the use-case of saving pipeline runtime costs. Having saucectl check for the results at a later step in the pipeline, would defeat that purpose, since you'd be running that step in the pipeline, incurring pipeline runtime costs.

**Review by sweeneyskirt-sl — APPROVED** [review]

**Comment by wswebcreation** [comment]
Thanks @alexplischke 

I understand we can't do this we SauceCTL, because that would defeat the purpose, but...., are we getting back for example a jobID, or can we suggest with APIs, use build names and so on how to retrieve the information in a later stadium. 
This now feels like "use our fire and forget" and good luck finding the information in our platform (and don't get me wrong)

**Comment by alexplischke** [comment]
Oh for sure, all job IDs are still printed out!

**Comment by wswebcreation** [comment]
Awesome, I'll start playing with it and see if I can come up with something to get the status

**Pull request merged**
