### PR TITLE
WIP: Dev deploy preview 

### PR DESCRIPTION
**Pull request by lysannep**
### Description
Rather than implementing something new (like Netlify) for deploy previews, this PR updates the existing manual `deploy-to-dev.yml` workflow used to deploy changes to the [docs dev site](https://docs.dev.saucelabs.net/). The workflow will:
- automatically run on pull requests to create the deploy preview when a commit is pushed, and
- add a [GitHub Action](https://github.com/unsplash/comment-on-pr) to add a [PR comment](https://github.com/saucelabs/sauce-docs/pull/2054#issuecomment-1572781287) with a link for the deploy preview

### Motivation and Context
https://github.com/saucelabs/sauce-docs/issues/2042

Previously, deploying changes to the dev environment was a manual process:
1. Go to **Actions**.
2. Select [**Deploy to Dev**](https://github.com/saucelabs/sauce-docs/actions/workflows/deploy-to-dev.yml).
3. Select **Run Workflow**.
4. Select the **branch** to deploy, then click **Run workflow**.

The goal is to make it easier for others to contribute to our docs without having to set up a local dev environment.

### Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### CODE REVIEW

**Comment by lysannep** [comment]
> Deploy preview ready for 2054! https://docs.dev.saucelabs.net built from [b8904e3](https://github.com/saucelabs/sauce-docs/commit/b8904e3e181040da0a7da6a9f54b047c5fb85a5a)

I can see my test changes in the deploy preview: https://docs.dev.saucelabs.net/error-reporting/workflow-integrations/issue-tracking/jira/

**Review by aoleszyn — APPROVED** [review]

**Review by diemol — COMMENTED** [review]
This is a good start! Thanks, @lysannep!

I guess the manual deploy is/was needed because the deployment gets overwritten, right? So, if I open a PR, the dev environment would have my PR changes. But if you open a PR afterwards, it would overwrite the dev environment.

Should we merge with this constraint? Or should we figure out if we can have different paths for each PR?

**Comment by diemol** [comment]
@lysannep I found this yesterday, would you mind if I try this in a separate PR?

https://github.com/marketplace/actions/deploy-pr-preview

**Comment by lysannep** [comment]
> @lysannep I found this yesterday, would you mind if I try this in a separate PR?
> 
> https://github.com/marketplace/actions/deploy-pr-preview

@diemol No, please go ahead. The GitHub Action looks like a better approach. Thanks for your help!

**Comment by lysannep** [comment]
Merging with this constraint --  A new deploy preview will be created when the main branch is merged into the working branch to keep it up to date.

> This is a good start! Thanks, @lysannep!
> 
> I guess the manual deploy is/was needed because the deployment gets overwritten, right? So, if I open a PR, the dev environment would have my PR changes. But if you open a PR afterwards, it would overwrite the dev environment.
> 
> Should we merge with this constraint? Or should we figure out if we can have different paths for each PR?

**Comment by diemol** [comment]
Thank you for continuing this, I will try to find time to implement the alternative.

**Pull request merged**
