### PR TITLE
Refactoring Best Practices content -> Test Config moved

### PR DESCRIPTION
**Pull request by lauramthomas**
**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sweeneyskirt-sl — COMMENTED** [review]
Hey @lauramthomas -- Did you mean for the 2 js-test-config images to be included in this PR? They seem unrelated to the Best Practices stuff, so I am just double-checking.

**Comment by lauramthomas** [comment]
Yes! As part of the BP content re-structuring, I had to move the Test Config content.

**Review by sweeneyskirt-sl — CHANGES_REQUESTED** [review]
Okay cool on the images. However....looks like deleting these files has resulted in some broken links: https://github.com/saucelabs/sauce-docs/pull/425/checks?check_run_id=2739124455

You'll need to fix them before we can merge :)

**Comment by lauramthomas** [comment]
Of course it did. I'll fix them now.

**Comment by lauramthomas** [comment]
@sweeneyskirt-sl Fixed--I think. Do I need to create a new PR or can you go from here?

**Review by sweeneyskirt-sl — APPROVED** [review]
Looks good. All tests are passing. :)

**Pull request merged**
